version: '3.5'

networks:
  localhost: { }

volumes:
  wordpress_dir:
    name: wordpress_dir
    driver: local
    driver_opts:
      device: /home/inception/data/srcs/requirements/wordpress/content
      o: bind
      type: none
  mariadb_dir:
    name: mariadb_dir
    driver: local
    driver_opts:
      device: /home/inception/data/srcs/requirements/mariadb/database
      o: bind
      type: none

services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb_dir:/var/lib/mysql
    networks:
      - localhost
    env_file: .env
    restart: always
  
  wordpress:
    build:
      context: ./requirements/wordpress
    #image: wordpress
    volumes:
      - wordpress_dir:/var/www/html
    depends_on:
      - mariadb
    networks:
      - localhost
    restart: always
    env_file: .env
  
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_dir:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - localhost