version: '3.5'

networks:
  localhost: { }

volumes:
  wordpress_dir:
    name: wordpress_dir
    driver: local
    driver_opts:
      device: /home/inception/data/srcs/wp-content
      o: bind
      type: none
  mariadb_dir:
    name: mariadb_dir
    driver: local
    driver_opts:
      device: /home/inception/data/srcs/mariadb
      o: bind
      type: none

services:
  mariadb:
    build: ./mariaDB
    volumes:
      - mariadb_dir:/var/lib/mysql
    networks:
      - localhost
    env_file: secrets.env
    restart: always
  
  wordpress:
    build:
      context: ./wordpress
    image: wordpress
    volumes:
      - wordpress_dir:/var/www/html
    depends_on:
      - mariadb
    networks:
      - localhost
    restart: always
    env_file: secrets.env
  
  nginx:
    build: ./nginx
    ports:
      - 443:443
    volumes:
      - wordpress_dir:/var/www/html
    depends_on:
      - wordpress
    links:
      - wordpress
    restart: always
    networks:
      - localhost